# GET http://localhost:5000/subscribers

# ###

# POST http://localhost:5000/subscribers

# Content-Type: application/json


# {
#     "name": "Omodu Uche",
#     "subscribedToChannel": "qgatss unleashed" 
# }  